AUTHOR="Simon Alman <haven@thehavennet.org.uk>"
DEFAULT_BUILDER="thehaven/bob"
BUILD_ENGINE="docker"

#Additional values taken from global kubler.conf:
IMAGE_TAG="${IMAGE_TAG:-$(date +%Y%m%d)}"
PORTAGE_DATE="${PORTAGE_DATE:-latest}"
MIRROR="${MIRROR:-https://haven:APZ8w6Eg1VEjw3RGQ1VrZt1eQb@artifactory.thehavennet.org.uk/artifactory/gentoo-mirror/}"
DOWNLOAD_PATH="${DOWNLOAD_PATH:-${_KUBLER_DIR}/tmp/downloads}"
BOB_GENTOO_MIRRORS="${BOB_GENTOO_MIRRORS:-${MIRROR}}"
BOB_FEATURES="${BOB_FEATURES:-parallel-fetch nodoc noinfo noman binpkg-multi-instance}"
BOB_EMERGE_DEFAULT_OPTS="${BOB_EMERGE_DEFAULT_OPTS:--b -k --binpkg-respect-use=y}"
BOB_TIMEZONE="${BOB_TIMEZONE:-UTC}"
BOB_MAKEOPTS="${BOB_MAKEOPTS:--j5}"
