FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

ADD rootfs.tar /

VOLUME ["/etc/exim","/etc/mail","/var/spool/mail"]

EXPOSE 25/tcp
EXPOSE 465/tcp
EXPOSE 587/tcp

USER mail
CMD ["/usr/sbin/exim -bdf -q15m"]
