FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

ADD rootfs.tar /

VOLUME ["/var/lib/sonarr"]
EXPOSE 9117

HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -f http://localhost:9117/ || exit 1

USER sonarr
CMD ["/usr/bin/mono", "/usr/share/work/NzbDrone/NzbDrone.exe", "-nobrowser"]
