{
	'insert_blank_line' : False,
	'disable_font_rescaling' : False,
	'line_height' : 0.0,
	'keep_ligatures' : False,
	'input_encoding' : None,
	'minimum_line_height' : 120.0,
	'remove_paragraph_spacing' : False,
	'smarten_punctuation' : True,
	'font_size_mapping' : None,
	'base_font_size' : 0.0,
	'asciiize' : False,
	'remove_paragraph_spacing_indent_size' : 1.5,
	'extra_css' : None,
	'linearize_tables' : False,
	'change_justification' : u'original',
}