FROM ${IMAGE_PARENT}
LABEL maintainer="${MAINTAINER}"

ADD rootfs.tar /
ADD calibre.tar /calibre

EXPOSE 8080/tcp

VOLUME ["/calibre", "/storage"]
COPY docker-healthcheck.sh /usr/bin/docker-healthcheck
HEALTHCHECK --interval=60s --timeout=5s --start-period=5s --retries=3 CMD ["docker-healthcheck"]
WORKDIR /calibre
USER calibre
CMD ["calibre-server --userdb /storage/users.sqlite --enable-auth /storage"]
