FROM ${IMAGE_PARENT}
LABEL maintainer ${MAINTAINER}

ADD rootfs.tar /

VOLUME ["/etc/radicale", "/var/lib/radicale", "/var/log/radicale"]
USER radicale
EXPOSE 5232/TCP
HEALTHCHECK --interval=5m --timeout=3s \
  CMD curl -f http://localhost:5232/ || exit 1

CMD ["/usr/bin/python3.6", "/usr/lib/python-exec/python3.6/radicale"]
