FROM ${IMAGE_PARENT}
LABEL maintainer="${MAINTAINER}"

ADD rootfs.tar /

COPY docker-healthcheck.sh /usr/bin/docker-healthcheck
HEALTHCHECK --interval=60s --timeout=5s --start-period=5s --retries=3 CMD ["docker-healthcheck"]

# Provide a writable mount point for downloads by default
VOLUME ["/media"]

# Run as non-root by default
USER 1000:1000

# Default execution
ENTRYPOINT ["/opt/scripts/yt-dlp.sh"]
CMD ["--foreground"]
