FROM ${IMAGE_PARENT}
LABEL maintainer="${MAINTAINER}"

ADD rootfs.tar /

COPY files/run_bind.sh /
COPY files/named.conf.tmpl /
COPY docker-healthcheck.sh /usr/bin/docker-healthcheck
HEALTHCHECK --interval=60s --timeout=5s --start-period=5s --retries=3 CMD ["docker-healthcheck"]
EXPOSE 53/tcp
EXPOSE 53/udp
EXPOSE 953/tcp
VOLUME ["/etc/ssl", "/etc/bind", "/var/bind", "/var/log/bind"]
USER named
WORKDIR /var/bind
CMD ["/run_bind.sh"]
