node {
    def app

    stage('Clone repository') {
        /* clone repo to our workspace */

        checkout scm
    }

    stage('Build image') {
        /* Build docker in docker image */
	app = docker.build("docker/salman/c7terraform")
    }

    stage('Test image') {
        app.inside {
            sh 'terraform --version'
        }
    }

    stage('Push image') {
        /* Ppush the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
        docker.withRegistry('https://repocache.nonprod.ppops.net', 'repocache-credentials') {
            app.push("${env.BUILD_NUMBER}")
            app.push("latest")
        }
    }
}
